// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: module/shelf/shelfPb/shelfPb.proto

package shelfPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShelfGrpcService_SearchUserShelf_FullMethodName = "/shelfPb.ShelfGrpcService/SearchUserShelf"
)

// ShelfGrpcServiceClient is the client API for ShelfGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShelfGrpcServiceClient interface {
	SearchUserShelf(ctx context.Context, in *SearchUserShelfReq, opts ...grpc.CallOption) (*SearchUserShelfRes, error)
}

type shelfGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShelfGrpcServiceClient(cc grpc.ClientConnInterface) ShelfGrpcServiceClient {
	return &shelfGrpcServiceClient{cc}
}

func (c *shelfGrpcServiceClient) SearchUserShelf(ctx context.Context, in *SearchUserShelfReq, opts ...grpc.CallOption) (*SearchUserShelfRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUserShelfRes)
	err := c.cc.Invoke(ctx, ShelfGrpcService_SearchUserShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShelfGrpcServiceServer is the server API for ShelfGrpcService service.
// All implementations must embed UnimplementedShelfGrpcServiceServer
// for forward compatibility.
type ShelfGrpcServiceServer interface {
	SearchUserShelf(context.Context, *SearchUserShelfReq) (*SearchUserShelfRes, error)
	mustEmbedUnimplementedShelfGrpcServiceServer()
}

// UnimplementedShelfGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShelfGrpcServiceServer struct{}

func (UnimplementedShelfGrpcServiceServer) SearchUserShelf(context.Context, *SearchUserShelfReq) (*SearchUserShelfRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserShelf not implemented")
}
func (UnimplementedShelfGrpcServiceServer) mustEmbedUnimplementedShelfGrpcServiceServer() {}
func (UnimplementedShelfGrpcServiceServer) testEmbeddedByValue()                          {}

// UnsafeShelfGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShelfGrpcServiceServer will
// result in compilation errors.
type UnsafeShelfGrpcServiceServer interface {
	mustEmbedUnimplementedShelfGrpcServiceServer()
}

func RegisterShelfGrpcServiceServer(s grpc.ServiceRegistrar, srv ShelfGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedShelfGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShelfGrpcService_ServiceDesc, srv)
}

func _ShelfGrpcService_SearchUserShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserShelfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfGrpcServiceServer).SearchUserShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfGrpcService_SearchUserShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfGrpcServiceServer).SearchUserShelf(ctx, req.(*SearchUserShelfReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShelfGrpcService_ServiceDesc is the grpc.ServiceDesc for ShelfGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShelfGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shelfPb.ShelfGrpcService",
	HandlerType: (*ShelfGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUserShelf",
			Handler:    _ShelfGrpcService_SearchUserShelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "module/shelf/shelfPb/shelfPb.proto",
}
