// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.14.0
// source: module/shelf/shelfPb/shelfPb.proto

package shelfPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchUserShelfReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId uint64 `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
}

func (x *SearchUserShelfReq) Reset() {
	*x = SearchUserShelfReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_shelf_shelfPb_shelfPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserShelfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserShelfReq) ProtoMessage() {}

func (x *SearchUserShelfReq) ProtoReflect() protoreflect.Message {
	mi := &file_module_shelf_shelfPb_shelfPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserShelfReq.ProtoReflect.Descriptor instead.
func (*SearchUserShelfReq) Descriptor() ([]byte, []int) {
	return file_module_shelf_shelfPb_shelfPb_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUserShelfReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchUserShelfReq) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type SearchUserShelfRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (x *SearchUserShelfRes) Reset() {
	*x = SearchUserShelfRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_module_shelf_shelfPb_shelfPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchUserShelfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserShelfRes) ProtoMessage() {}

func (x *SearchUserShelfRes) ProtoReflect() protoreflect.Message {
	mi := &file_module_shelf_shelfPb_shelfPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserShelfRes.ProtoReflect.Descriptor instead.
func (*SearchUserShelfRes) Descriptor() ([]byte, []int) {
	return file_module_shelf_shelfPb_shelfPb_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUserShelfRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_module_shelf_shelfPb_shelfPb_proto protoreflect.FileDescriptor

var file_module_shelf_shelfPb_shelfPb_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x66, 0x2f, 0x73,
	0x68, 0x65, 0x6c, 0x66, 0x50, 0x62, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x66, 0x50, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x68, 0x65, 0x6c, 0x66, 0x50, 0x62, 0x22, 0x46, 0x0a,
	0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x65, 0x6c, 0x66,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x32, 0x5f, 0x0a, 0x10, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x47,
	0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x12, 0x1b, 0x2e,
	0x73, 0x68, 0x65, 0x6c, 0x66, 0x50, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x68, 0x65, 0x6c, 0x66, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x65,
	0x6c, 0x66, 0x50, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x68, 0x65, 0x6c, 0x66, 0x52, 0x65, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x69, 0x74, 0x41, 0x73, 0x61, 0x77, 0x61, 0x6e,
	0x69, 0x72, 0x61, 0x6d, 0x6f, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x73, 0x68,
	0x65, 0x6c, 0x66, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x66, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_module_shelf_shelfPb_shelfPb_proto_rawDescOnce sync.Once
	file_module_shelf_shelfPb_shelfPb_proto_rawDescData = file_module_shelf_shelfPb_shelfPb_proto_rawDesc
)

func file_module_shelf_shelfPb_shelfPb_proto_rawDescGZIP() []byte {
	file_module_shelf_shelfPb_shelfPb_proto_rawDescOnce.Do(func() {
		file_module_shelf_shelfPb_shelfPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_module_shelf_shelfPb_shelfPb_proto_rawDescData)
	})
	return file_module_shelf_shelfPb_shelfPb_proto_rawDescData
}

var file_module_shelf_shelfPb_shelfPb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_module_shelf_shelfPb_shelfPb_proto_goTypes = []any{
	(*SearchUserShelfReq)(nil), // 0: shelfPb.SearchUserShelfReq
	(*SearchUserShelfRes)(nil), // 1: shelfPb.SearchUserShelfRes
}
var file_module_shelf_shelfPb_shelfPb_proto_depIdxs = []int32{
	0, // 0: shelfPb.ShelfGrpcService.SearchUserShelf:input_type -> shelfPb.SearchUserShelfReq
	1, // 1: shelfPb.ShelfGrpcService.SearchUserShelf:output_type -> shelfPb.SearchUserShelfRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_shelf_shelfPb_shelfPb_proto_init() }
func file_module_shelf_shelfPb_shelfPb_proto_init() {
	if File_module_shelf_shelfPb_shelfPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_module_shelf_shelfPb_shelfPb_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUserShelfReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_module_shelf_shelfPb_shelfPb_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchUserShelfRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_module_shelf_shelfPb_shelfPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_shelf_shelfPb_shelfPb_proto_goTypes,
		DependencyIndexes: file_module_shelf_shelfPb_shelfPb_proto_depIdxs,
		MessageInfos:      file_module_shelf_shelfPb_shelfPb_proto_msgTypes,
	}.Build()
	File_module_shelf_shelfPb_shelfPb_proto = out.File
	file_module_shelf_shelfPb_shelfPb_proto_rawDesc = nil
	file_module_shelf_shelfPb_shelfPb_proto_goTypes = nil
	file_module_shelf_shelfPb_shelfPb_proto_depIdxs = nil
}
