name: Build and Deploy to GKE

on:
  push:
    branches:
      - main # Deploy on main branch merges
  pull_request:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1 # Cluster name
  GKE_ZONE: asia-southeast1-b # Cluster zone
  IMAGE: book-store # Image name
  IMAGE_TAG: latest # Image tag
  GAR_ZONE: asia-southeast1 # Artifact registry zone
  GAR_REPO: book-store # Artifact registry repository

jobs:
  ci:
    name: CI Setup, Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Test
        run: go test -v ./...

      # Configure Docker to use the gcloud command-line tool for authentication
      - name: Docker configuration
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_ZONE-docker.pkg.dev

      # Build the Docker image
      - name: Build
        run: |
          docker build --platform linux/amd64 -f build/Dockerfile -t "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG" \
            --build-arg
